# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Network_pb2 as Network__pb2


class NetworkStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallBack = channel.unary_unary(
                '/Testgrpc.Network/CallBack',
                request_serializer=Network__pb2.Request.SerializeToString,
                response_deserializer=Network__pb2.Reply.FromString,
                )


class NetworkServicer(object):
    """Missing associated documentation comment in .proto file"""

    def CallBack(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NetworkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallBack': grpc.unary_unary_rpc_method_handler(
                    servicer.CallBack,
                    request_deserializer=Network__pb2.Request.FromString,
                    response_serializer=Network__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Testgrpc.Network', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Network(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def CallBack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Testgrpc.Network/CallBack',
            Network__pb2.Request.SerializeToString,
            Network__pb2.Reply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
