# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Network.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Network.proto',
  package='Testgrpc',
  syntax='proto3',
  serialized_options=b'\n\000B\007MyProtoP\001\242\002\002MY',
  serialized_pb=b'\n\rNetwork.proto\x12\x08Testgrpc\"\x1d\n\x07Request\x12\x12\n\nclientName\x18\x01 \x01(\t\"\x18\n\x05Reply\x12\x0f\n\x07message\x18\x01 \x01(\t2;\n\x07Network\x12\x30\n\x08\x43\x61llBack\x12\x11.Testgrpc.Request\x1a\x0f.Testgrpc.Reply\"\x00\x42\x12\n\x00\x42\x07MyProtoP\x01\xa2\x02\x02MYb\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Testgrpc.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientName', full_name='Testgrpc.Request.clientName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=56,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='Testgrpc.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='Testgrpc.Reply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'Network_pb2'
  # @@protoc_insertion_point(class_scope:Testgrpc.Request)
  })
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'Network_pb2'
  # @@protoc_insertion_point(class_scope:Testgrpc.Reply)
  })
_sym_db.RegisterMessage(Reply)


DESCRIPTOR._options = None

_NETWORK = _descriptor.ServiceDescriptor(
  name='Network',
  full_name='Testgrpc.Network',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=84,
  serialized_end=143,
  methods=[
  _descriptor.MethodDescriptor(
    name='CallBack',
    full_name='Testgrpc.Network.CallBack',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NETWORK)

DESCRIPTOR.services_by_name['Network'] = _NETWORK

# @@protoc_insertion_point(module_scope)
